# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
       ROLE_SONATA_FOO_READER:
           - ROLE_SONATA_ADMIN_DEMO_FOO_LIST
           - ROLE_SONATA_ADMIN_DEMO_FOO_VIEW
       ROLE_SONATA_FOO_EDITOR: 
           - ROLE_SONATA_ADMIN_DEMO_FOO_CREATE
           - ROLE_SONATA_ADMIN_DEMO_FOO_EDIT
       ROLE_SONATA_FOO_ADMIN:
           - ROLE_SONATA_ADMIN_DEMO_FOO_DELETE
           - ROLE_SONATA_ADMIN_DEMO_FOO_EXPORT
           
       ROLE_STAFF:             [ROLE_USER, ROLE_SONATA_FOO_READER]
       ROLE_ADMIN:             [ROLE_STAFF, ROLE_SONATA_FOO_EDITOR, ROLE_SONATA_FOO_ADMIN]
       ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
       
       ROLE_ALL_ADMIN:         [ROLE_STAFF, ROLE_SONATA_FOO_ALL]
    
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
     
    providers:
        fos_userbundle:
           id: fos_user.user_provider.username

    firewalls:
        main:
           pattern: ^/
           form-login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
           logout: true
           anonymous: true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access_control:
       - { path: ^/wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # AsseticBundle paths used when using the controller for assets
       - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # URL of FOSUserBundle which need to be available to anonymous users
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY } # for the case of a failed login
       - { path: ^/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/request-reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/send-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/check-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/user/reset-password/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
       - { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
       
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
       
    access_decision_manager:
        strategy: unanimous
    acl:
        connection: default
